config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'

  get 'orders/show'

  get 'order_details/index'

  get 'order_details/show'

  resources :order_details
  
  resources :orders, only: [:index,:show,:new,:create]
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
        has_many :order_details
        accepts_nested_attributes_for :order_details
        has_many :products, through: :order_details

        def order_total_price
                order_details.sum(:total_price);
        end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
	before_save {self.total_price=product.price*self.count}	

	belongs_to :product # must be singular
	belongs_to :order, optional: true
	
	validates :count, numericality: {greater_than: 0}
end

app/models/product.rb
class Product < ApplicationRecord
	validates :name,:price, presence:true
	validates :name, length:{minimum:2,maximum:100}
	validates_numericality_of :price, greater_than:100

	has_many :order_details # must be plural form
	has_many :orders, through: :order_details

	def sales_count
		return order_details.sum(:count)
	end
	def self.sales_ranking(count=10)
		self.joins(:order_details).group('order_details.product_id').order('SUM(order_details.count) DESC').first(count)
	end
	def format_content
		"#{name} #{price}"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/order_details_controller.rb
class OrderDetailsController < ApplicationController
  before_action :set_detail, only: [:show,:edit,:update,:destroy]
  def index
	@order_details=OrderDetail.all # <= added
  end

  def show
	#@detail=OrderDetail.find(params[:id])
  end
  def new
        @detail=OrderDetail.new
  end
  #It is makeshift to confirm value of POST from FORM
  def create
	@detail = OrderDetail.new(order_details_params)
	if @detail.save
		redirect_to @detail
	else 
		render action: 'new'
	end
  end
  def edit
	#@detail=OrderDetail.find(params[:id])
  end
  def update
	#@detail=OrderDetail.find(params[:id])

	if @detail.update(order_details_params)
		redirect_to order_details_path#redirect_to @detail
	else
		render action:'edit'
	end
  end
  def destroy
	#@detail=OrderDetail.find(params[:id])
	@detail.destroy
	redirect_to order_details_url
  end

  private
  def order_details_params
      params.require(:order_detail).permit(:order_id,:product_id,:count)
  end

  def set_detail
	@detail=OrderDetail.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
	@orders=Order.all
  end

  def show
    @detail=Order.find(params[:id])
  end

  def new
    @order=Order.new
    3.times {@order.order_details.build}#It will be able to select three products
    @products=Product.all
  end

  def create
    @order=Order.new(order_params)
    @products=Product.all

    if @order.save
      redirect_to @order
    else
      render action:'new'
    end
  end

  private
  def order_params
    params.require(:order).permit(order_details_attributes:[:product_id,:count])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/order_details/edit.html.erb
rder detail</h1>

<%= form_for(@detail) do |f| %>
  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.collection_select(:order_id, Order.all, :id, :id) %>
  </div>
  <div class="field">
  <%= f.label :product_id %><br>
  <%= f.collection_select(:product_id, Product.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :count %><br>
    <%= f.text_field :count %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Show', @detail %>
<%= link_to 'Back', order_details_path %>

app/views/order_details/index.html.erb
<h1>Order Detail List</h1>
<!--Find me in app/views/order_details/index.html.erb-->

<table class="table">
	<thead>
		<tr>
			<th>Order ID</th>
			<th>Product ID</th>
			<th>Product Name</th>
			<th>Order count</th>
			<th>Sum of order price</th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
	<%@order_details.each do |detail|%>
		<tr>
			<td><%=detail.order_id%></td>
			<td><%=detail.product_id%></td>
			<td><%=detail.product.name%></td>
			<td><%=detail.count%></td>
			<td><%=detail.total_price%></td>
			<td><%=link_to 'Show',detail%></td>
			<td><%=link_to 'edit',edit_order_detail_path(detail)%>|<%=link_to 'Deletion', detail, method: :delete,data:{confirm:'Do you want to delete?'}%></td>
		</tr>
	<%end%>
	</tbody>
</table>
<%=link_to "New Order Detail",new_order_detail_path%>

app/views/order_details/new.html.erb
<!--I created this file myself(not generated)-->
<h1>Create Order Detail</h1>

<%= form_for(@detail) do |f| %>
  <div class="field">
	<%=f.label :order_id%><br/>
	<%=f.collection_select(:order_id,Order.all,:id,:id)%>
  </div>
  <div class="field">
        <%=f.label :product_id%><br/>
        <%=f.collection_select(:product_id,Product.all,:id,:format_content)%>
  </div>
  <div class="field">
        <%=f.label :count%><br/>
        <%=f.text_field :count%>
  </div>
  <div class="actions">
	<%=f.submit%>
  </div>
<%end%>

<%= link_to 'Back', order_details_path%>

app/views/order_details/show.html.erb
<h1>Order Details Information</h1>
<!--Find me in app/views/order_details/show.html.erb-->
<p>
	<strong>Order ID</strong>
	<%=@detail.order_id%>
</p>
<p>
        <strong>Product ID</strong>
        <%=@detail.product_id%>
</p>
<p>
        <strong>Product Name</strong>
        <%=@detail.product.name%>
</p>
<p>
        <strong>Order Count</strong>
        <%=@detail.count%>
</p>
<p>
        <strong>Sum of order price</strong>
        <%=@detail.total_price%>
</p>

<%= link_to 'Back', order_details_path %>

app/views/orders/index.html.erb
<h1>Order List</h1>
<!--Find me in app/views/orders/index.html.erb-->

<table class="table">
	<thead>
		<tr>
			<th>Ordered Time</th>
			<th>Sum of Order Price</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<%@orders.each do |eachorder|%>
			<tr>
				<td><%=eachorder.created_at%></td>
				<td><%=eachorder.order_total_price%></td>
				<td><%=link_to 'Show',eachorder%></td>
			</tr>
		<%end%>
	</tbody>
</table>

app/views/orders/new.html.erb
<%=form_for @order,:html=>{:class=>'form-horizontal'} do |f|%>
	<%=f.fields_for :order_details do |od|%>
	<div class="form-group">
		<div class="col-xs-2"><%=od.label :product_id, :class=>"control-label"%></div>
		<div class="col-xs-10">
			<%=od.collection_select(:product_id,@products,:id,:name,:class=>"form-control")%>
			</div>
	</div>
	<div class="form-group">
		<div class="col-xs-2"><%=od.label :count, :class=>"control-label"%></div>
		<div class="col-xs-10"><%=od.text_field :count, :class=>"form-control"%></div>
	</div>
	<%end%>

	<div class="actions">
		<%=f.submit%>
	</div>
<%end%>
</div>

app/views/orders/show.html.erb
<h1>Order Detail</h1>
<!--Find me in app/views/orders/show.html.erb-->

<table>
	<tr>
		<td>Order ID:</td>
		<td><%=@detail.id%></td>
	</tr>
	<tr>
		<td>Sum of order price:</td>
		<td><%=@detail.order_total_price%></td>
	</tr>
</table>
<table class="table">
        <thead>
                <tr>
                        <th>Product Name</th>
                        <th>Counts</th>
                        <th>Total Prices</th>
                </tr>
        </thead>
        <tbody>
        <%@detail.order_details.each do |detailitem|%>
                <tr>
                        <td><%=detailitem.product.name%></td>
                        <td><%=detailitem.count%></td>
                        <td><%=detailitem.total_price%></td>
		</tr>
	<%end%>
	</tbody>
</table>
<%= link_to 'All Orders',orders_index_path%>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>